server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: levo-schema-api

  datasource:
    url: jdbc:postgresql://localhost:5432/schemas
    username: username
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

logging:
  level:
    root: DEBUG
    org.springframework: DEBUG
    com.levo.schema: DEBUG
    com.levo.schemaapi: INFO
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

levo:
  storage:
    base-path: ./schema_storage
    max-file-size: 10MB
  schema:
    validation:
      strict-mode: true
      allow-extensions: true
  api:
    version: v1
    title: Levo Schema Management API
    description: API for managing schemas with versioning support

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /api-docs
